### ISSUE TITLE
Class 'Pvtl\VoyagerFrontend\Helpers\Layouts' not found

### ISSUE THREAD

**Issue by hamza-mostafa** [pvtl/voyager-forms#1]
Hey guys,
I bumped into this error while trying to create a new form

`vendor/pvtl/voyager-forms/src/Http/Controllers/FormController.php`

```

    public function create(Request $request)
    {
        Voyager::canOrFail('add_forms');
 
        return view('voyager-forms::forms.edit-add', [
            'dataType' => $this->getDataType($request),
            'layouts' => Layouts::getLayouts('voyager-forms'),
            'emailTemplates' => Layouts::getLayouts('voyager-forms', 'email-templates'),
        ]);
    }
```

**Comment by mcnamee** [comment]
Hi @hamza-mostafa 
Sorry you've experienced that. Can you please ensure you've got:

- At least __v0.2.1__ of this package
- At least __v0.5.0__ of [pvtl/voyager-frontend](https://github.com/pvtl/voyager-frontend) (should come as a dependency of voyager-forms v0.2.1)

**Comment by hamza-mostafa** [comment]
I've updated them .. and no error .. thanks for the swift update .. and this and the other packages ^^
