### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by SidharthRaveendran** [pvtl/voyager-forms#10]
Would there be any way to have a date picker field type?

**Comment by mcnamee** [comment]
@SidharthRaveendran I believe there's a `voyager::formfields.date` partial you could use.

Eg. In the `config/page-blocks.php`, within a block, you could add a field like:

```
        'hello_date' => [
            'field' => 'hello_date',
            'display_name' => 'Hello Date',
            'partial' => 'voyager::formfields.date',
            'required' => 0,
        ],
```
