### ISSUE TITLE
Grouping of form fields

### ISSUE THREAD

**Issue by SidharthRaveendran** [pvtl/voyager-forms#11]
It would be nice to group a couple of fields and have a heading for them, because large forms usually need to be broken down in to sections.

**Comment by mcnamee** [comment]
@SidharthRaveendran I like the idea - mind submitting a PR?

**Comment by Liam-PVTL** [comment]
We have now added this feature. 

Re-import the config file and run a migration on 0.4.5 to take advantage of the feature. More details in the readme!
