### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by mtayrek** [pvtl/voyager-forms#15]
![Capture](https://user-images.githubusercontent.com/22226583/57699319-27e88a80-7660-11e9-80b3-3d2e5ec55767.PNG)

**Comment by mcnamee** [comment]
Hi @mtayrek 
Can you please add your `composer.json` - I believe the error is indicating that you've got voyager 1.1.1 installed, but one of the dependencies in the tree requires a minimum of voyager 1.1.8.

Is that how you understand it?

**Comment by mtayrek** [comment]
Working after updating, thanks!
