### ISSUE TITLE
 Class 'AlgoliaSearch\Version' not found error message

### ISSUE THREAD

**Issue by tyndouf** [pvtl/voyager-forms#17]
Laravel 5.8
PHP 7.3
Voyager 1.2.3
Voyager-forms

Got the bellow error message when when clickin on the Save Settings button :

 Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'AlgoliaSearch\Version' not found.

Any idea what this error comes from?

Thanks.

**Comment by mcnamee** [comment]
Can you please try adding `SCOUT_DRIVER=tntsearch` to your `.env`
Does that fix? If so can you please submit a PR to add this to the Readme installation instructions?
