### ISSUE TITLE
The command "composer dump-autoload" failed. 

### ISSUE THREAD

**Issue by hermesalvesbr** [pvtl/voyager-forms#24]
`php artisan voyager-forms:install
Publishing Form assets, database, and config files
Copied Directory [/vendor/pvtl/voyager-forms/config] To [/config]
Publishing complete.
Dumping the autoloaded files and reloading all new files

   Symfony\Component\Process\Exception\ProcessFailedException  : The command "composer dump-autoload" failed.

Exit Code: 127(Command not found)

Working directory: /Users/hermesalves/www/cipagon

Output:
================

Error Output:
================
sh: composer: command not found

  at /Users/hermesalves/www/cipagon/vendor/symfony/process/Process.php:254
    250|      */
    251|     public function mustRun(callable $callback = null, array $env = []): self
    252|     {
    253|         if (0 !== $this->run($callback, $env)) {
  > 254|             throw new ProcessFailedException($this);
    255|         }
    256| 
    257|         return $this;
    258|     }

  Exception trace:

  1   Symfony\Component\Process\Process::mustRun()
      /Users/hermesalves/www/cipagon/vendor/pvtl/voyager-forms/src/Commands/InstallCommand.php:64

  2   Pvtl\VoyagerForms\Commands\InstallCommand::handle()
      /Users/hermesalves/www/cipagon/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  Please use the argument -v to see more details.
`

This error after install, i'm using this version:

`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "cornford/googlmapper": "2.*",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0",
        "pvtl/voyager-forms": "^0.4.1",
        "tcg/voyager": "^1.3"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "repositories": {
        "hooks": {
            "type": "composer",
            "url": "https://larapack.io"
        }
    }
}`

**Comment by Liam-PVTL** [comment]
@hermesalvesbr thanks for opening an issue. What happens if you run composer dump-autoload from the root of your project directory?

**Comment by Liam-PVTL** [comment]
Closing because I can install the package fine with no errors & inactivity.
