### ISSUE TITLE
Call to a member function getTranslatedAttribute() on null 

### ISSUE THREAD

**Issue by salvationws** [pvtl/voyager-forms#27]
Hello,
on view enquiries there is an error.

Symfony\Component\Debug\Exception\FatalThrowableError
Call to a member function getTranslatedAttribute() on null 

http://website/admin/enquiries?filter=contains&key=id&s=1 

![image](https://user-images.githubusercontent.com/16476638/73646297-965bf580-4692-11ea-89d0-c40246218876.png)

**Comment by ahmadsyamim** [comment]
Probably related to #68 https://github.com/pvtl/voyager-frontend/issues/68

**Comment by Liam-PVTL** [comment]
Please refresh your BREAD by navigating to /admin/bread/enquiries/edit & clicking submit.

If anyone can reliably reproduce this & comes across this comment in the future, please let me know what those steps are so we can attempt to fix the underlying issue.
