### ISSUE TITLE
Adjusting any bread options on Enquiry causes #2 to come back

### ISSUE THREAD

**Issue by mallardduck** [pvtl/voyager-forms#29]
Per my comment in #2 - I experienced this issue and through some reviewing of that issue and the way it was solved believe the explanation is rather trivial.

After I installed this package in a project/site I am building I adjusted the display text for the Bread's columns to sooth my OCD about Capitalizations. Seeing as Voyager knew a data column existed, but didn't have a DataRow yet - I believe that voyager set this column to all the defaults and thus blew up on me.

Ultimately I feel https://github.com/pvtl/voyager-forms/commit/d2b4cd49737a16502aebed7d6ab0844a0aa963e8 could be expanded upon to improve this aspect of the situation, this should help prevent _future_ installations from experiencing this issue when a user edits the Bread.

**Comment by Liam-PVTL** [comment]
Looks great. 

Can't thank you enough for both identifying & fixing this issue.
