### ISSUE TITLE
Incompatible versions

### ISSUE THREAD

**Issue by lucasheer** [pvtl/voyager-forms#31]
Hello!

When I try to install voyager forms, it says it is incompatible with voyager-frontend 1.0

Problem 1
    - Installation request for pvtl/voyager-forms ^0.4.7 -> satisfiable by pvtl/voyager-forms[0.4.7].
    - pvtl/voyager-forms 0.4.7 requires pvtl/voyager-frontend ^0.9 -> satisfiable by pvtl/voyager-frontend[0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8] but these conflict with your requirements or minimum-stability.

Is it safe to force an install?

Thank you!

**Comment by tfmm** [comment]
#32 looks like it should solve this issue if a maintainer could take a look and potentially merge it.
