### ISSUE TITLE
Order function isn`t working

### ISSUE THREAD

**Issue by maxmadknight** [pvtl/voyager-forms#4]
Apparently the Voyager added sorting and now the routing is not working correctly when I try to change the order I get an error about the fact that the Form entity can not be found

"Too few arguments to function Illuminate\Database\Eloquent\Model::setAttribute(), 1 passed in vendor/laravel/framework/src/Illuminate/Database/Eloquent/Concerns/HasAttributes.php on line 592 and exactly 2 expected"

Error apears in this function ($i->$column equal to null )

vendor/tcg/voyager/src/Http/Controllers/VoyagerBaseController.php:488

**Comment by maxmadknight** [comment]
@Jean-PierreGassin @mcnamee Any news!?

**Comment by lukewmoore** [comment]
Fixed Voyager conflict in https://github.com/pvtl/voyager-forms/commit/b7824b96a3211231218a01514efaa64a768afd60.
