### ISSUE TITLE
upload file

### ISSUE THREAD

**Issue by tythompson85** [pvtl/voyager-forms#7]
Is there a way to allow for a file upload field?

**Comment by lukewmoore** [comment]
Hi @tythompson85, unfortunately this will take more than adding file inputs to the configuration and to the render view, storage will need to be handled among other things. I'll consider adding this to core.

**Comment by viaativaweb** [comment]
Hi @tythompson85, recently released a new update that allows you to insert a file input.

**Comment by tythompson85** [comment]
Thank you very much @viaativaweb
