### ISSUE TITLE
Add Reply in Inquiries!

### ISSUE THREAD

**Issue by wooooh** [pvtl/voyager-forms#9]
Hi buddy, first thank you so much for you great work.

a question, any way to implement reply Inquiries directly from the panel?

thanks in advances for any info!
Regards

**Comment by lukewmoore** [comment]
Hi @wooooh, there currently isn't a way to reply to enquiries via the admin panel, automatically or otherwise. If that's not what you're looking for, can you please provide more information?

**Comment by wooooh** [comment]
> Hi @wooooh, there currently isn't a way to reply to enquiries via the admin panel, automatically or otherwise. If that's not what you're looking for, can you please provide more information?

Hi buddy, thank you for you reply, Yes that was my question, your work is really good, you can recommend me a repository with all this function I need it, reply Inquiries directly from the panel?  many thanks in advance brother!
